In [2]:
import pandas as pd
import numpy as ny

In [3]:
data1_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
data2_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
data3_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [4]:
data1_df.shape

(4008, 11)

In [5]:
data2_df.shape

(996, 11)

In [6]:
data3_df.shape

(7070, 11)

In [7]:
for df in [data1_df, data2_df, data3_df]:
    df.columns = df.columns.str.lower()

In [8]:
data1_df = data1_df.rename(columns={"st":"state"})

In [9]:
data1_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [10]:
data2_df = data2_df.rename(columns={"st":"state"})

In [11]:
data2_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [12]:
data3_df.columns

Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [13]:
for df in [data1_df, data2_df, data3_df]:
    df.columns = df.columns.str.strip().str.replace(" ", "_")

In [14]:
combined_df = pd.concat([data1_df, data2_df,data3_df],axis=0, ignore_index=True)
combined_df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [15]:
combined_df.shape

(12074, 11)

In [16]:
duplicates = combined_df.duplicated().sum()

In [17]:
duplicates

np.int64(2939)

In [18]:
combined_df = combined_df.drop_duplicates().reset_index(drop=True)

In [19]:
combined_df.duplicated().sum()

np.int64(0)

In [20]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [21]:
df.shape

(10910, 27)

In [22]:
df.columns.unique()

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [23]:
pivot1 = df.pivot_table(
    index='sales_channel', 
    values='total_claim_amount',
    aggfunc='sum'
).round(2)

In [24]:
pivot1

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

In [25]:
pivot2 = df.pivot_table(
    index='gender', 
    columns='education', 
    values='customer_lifetime_value', 
    aggfunc='mean'
).round(2)

In [26]:
pivot2

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

In [27]:
bonus_table = df.pivot_table(
    index=['policy_type', 'month'], 
    values='number_of_open_complaints', 
    aggfunc='sum'
).reset_index()


bonus_table = bonus_table.rename(columns={'number_of_open_complaints': 'complaints'})

bonus_table

      policy_type  month   complaints
0  Corporate Auto      1   443.434952
1  Corporate Auto      2   385.208135
2   Personal Auto      1  1727.605722
3   Personal Auto      2  1453.684441
4    Special Auto      1    87.074049
5    Special Auto      2    95.226817